
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     device/usb/public/mojom/chooser_service.mojom
//

package org.chromium.device.mojom;

import org.chromium.mojo.bindings.DeserializationException;


public interface UsbChooserService extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends UsbChooserService, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<UsbChooserService, UsbChooserService.Proxy> MANAGER = UsbChooserService_Internal.MANAGER;


    void getPermission(
UsbDeviceFilter[] deviceFilters, 
GetPermissionResponse callback);

    interface GetPermissionResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<UsbDeviceInfo> { }


}
